[project]
name = "firecrawl-cbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "langchain>=0.3.27",
    "langgraph>=0.6.1",
    "torch>=2.7.1",
    "transformers>=4.54.1",
]
